require 'ciat'
require 'ciat/compiler_in_java'
require 'ciat/executor_of_parrot'

task :default do
  CIAT::Base.run_tests(make_compiler, CIAT::ExecutorOfParrot.new)
end

def make_compiler
  CIAT::CompilerInJava.new(classpath, 'org.norecess.hobbes.drivers.PIRCompiler')
end

def classpath
  Dir.glob('../lib/*.jar').join(':') + ":../bin"
end
