require 'ciat'
require 'ciat/compilers/java'
require 'ciat/executors/parrot'

task :ciat do
  CIAT::Suite.new(compiler, executor).run
end

def compiler
  classpath = Dir.glob('../lib/*.jar').join(':') + ":../bin"
  CIAT::Compilers::Java.new(classpath, 'org.norecess.hobbes.drivers.PIRCompiler')
end

def executor
  CIAT::Executors::Parrot.new
end
