require 'ciat'
require 'ciat/compilers/java'
require 'ciat/executors/java'
require 'ciat/executors/parrot'

task :default => :ciat

def classpath
  Dir.glob('../lib/*.jar').join(':') + ":../bin"
end

def compiler
  CIAT::Compilers::Java.new(classpath,
    'org.norecess.hobbes.drivers.PIRCompilerCLI',
    :description => 'Hobbes Compiler')
end

def interpreter
  CIAT::Executors::Java.new(classpath, 
    'org.norecess.hobbes.drivers.InterpreterCLI',
    :description => 'Hobbes Interpreter')
end

def executor
  CIAT::Executors::Parrot.new(:description => 'PIR VM', :processor_kind => CIAT::Processors::CompilationInterpreter.new)
end

task :ciat do
  Rake::Task['interpreter_tests'].invoke
  Rake::Task['compiler_tests'].invoke
end

CIAT::RakeTask.new(:compiler_tests) do |task|
  task.processors << compiler
  task.processors << executor
end

CIAT::RakeTask.new(:interpreter_tests) do |task|
  task.processors << interpreter
  task.report_filename = "interpreter.html"
end
