require 'ciat'
require 'ciat/compilers/java'
require 'ciat/executors/parrot'

task :default => :ciat

def compiler
  classpath = Dir.glob('../lib/*.jar').join(':') + ":../bin"
  CIAT::Compilers::Java.new(classpath, 'org.norecess.hobbes.drivers.PIRCompiler',
    :description => 'Hobbes Compiler')
end

def executor
  CIAT::Executors::Parrot.new(:description => 'PIR VM', :processor_kind => CIAT::Processors::CompilationInterpreter.new)
end

CIAT::RakeTask.new do |task|
  task.processors << compiler
  task.processors << executor
end
