require 'ciat'
require 'ciat/compilers/java'
require 'ciat/executors/java'
require 'ciat/executors/parrot'

task :default => :ciat

def classpath
  Dir.glob('../lib/*.jar').join(':') + ":../bin"
end

def compiler
  CIAT::Compilers::Java.new(classpath,
    'org.norecess.hobbes.drivers.PIRCompilerCLI',
    :description => 'Hobbes Compiler')
end

def interpreter
  CIAT::Executors::Java.new(classpath, 
    'org.norecess.hobbes.drivers.InterpreterCLI',
    :description => 'Hobbes Interpreter')
end

def executor
  CIAT::Executors::Parrot.new(:description => 'PIR VM',
    :processor_kind => CIAT::Processors::CompilationInterpreter.new,
    :libraries => ["../pirlib"])
end

task :ciat do
  ex = nil
  begin
    Rake::Task['interpreter_tests'].invoke
  rescue Exception => e
    ex = e
  end
  Rake::Task['compiler_tests'].invoke
  fail e if e
end

task :focused_tests => [:only_focused_tests, :ciat]

CIAT::RakeTask.new(:only_focused_tests) do |task|
  task.processors << interpreter
  task.folder = "ciat/let"
  task.report_title = "Focused Test: " + task.folder
  task.output_folder = "focused"
end

CIAT::RakeTask.new(:compiler_tests) do |task|
  task.processors << compiler
  task.processors << executor
  task.report_title = "Hobbes Compiler"
  task.output_folder = "compiler"
end

CIAT::RakeTask.new(:interpreter_tests) do |task|
  task.processors << interpreter
  task.report_title = "Hobbes Interpreter"
  task.output_folder = "interpreter"
end
